import SpotifyWrapper from 'spotify-wrapper'

const spotify = new SpotifyWrapper({
  token: 'BQDwowo7EuPRKnpkKzn6usXxpimclU5ovRXP1Ypfi3Jej94pALwjilGS9ey0eSqbSiTIDEOgo8vLZHh4dEFs-rok44NUecvESIHUG8P5u_1sUGXe7CgikRr5bf_Ny2EOBPwO-TdAAVCcVwym2-CTEsQ0Jv3D36YBvWIAPzikQqOtE0GRPS5o8RROYnfhy22w6JDmNSlb_JNFyGZMZE5yLzVvTQ8zjAv1deFjfYiyxY_CPnxevmuJqNlmWvoO0yLux4eEsQPdEqcE4-k'
})

export default spotify